### ISSUE TITLE
Phrasensuche

### ISSUE THREAD

**Issue by syslock** [syslock/ems#15]
Insbesondere für die Suche nach Tags, die aus Wortgruppen bestehen, wird eine Phrasensuche benötigt, da das derzeitige Verhalten die Suchanfrage `tag:Thema aus mehreren Wörtern` erzeugt, welche nach Beiträgen mit dem Schlagwort `Thema` und solchen mit den allgemeinen Begriffen `aus`, `mehreren`, `Wörtern` sucht, was zwar teilweis gewünschte Treffer liefert, aber auch falsche. Eine denkbare Suchsyntax für Phrasensuche wäre: `tag:"Thema aus merheren Wörtern"`. Wie der Volltextindex eine allgemeine Teilphrasensuche in längeren Texten realisieren kann, ist mir derzeit noch unklar, allerdings könnte man für Tags eine Ausnahme machen und sie immer auch in voller Länge in den Index legen, damit zumindest die eingebaute Themen-Suchfunktion erwartungsgemäß funktioniert.

**Comment by MetalsKiller64** [comment]
Aus meiner Sicht wäre es sinnvoll wenn die Suchfunktion auch nach Tags sucht die den angegebenen Suchstring nur teilweise enthalten. Das wäre zum Beispiel beim Hinzufügen eines Tags zu einem Beitrag nützlich.
Beispiel:
Zieltag: JavaScript
![tags_search1](https://cloud.githubusercontent.com/assets/4581816/8507756/e1cb554e-2250-11e5-9632-6c47dd632cbb.png)

Bei diesem Versuch wird "JavaScript" nicht gefunden, sondern nur vorgeschlagen einen neuen anzulegen.
![tags_search2](https://cloud.githubusercontent.com/assets/4581816/8507757/ec5df0c0-2250-11e5-8c8b-9b0e3e904622.png)

**Comment by syslock** [comment]
Das wär schön, ~~ist aber komplexer. Wir müssten dazu zumindest einen Präfixindex für alle Wörter haben.~~ 
`<snip>`
Edit: Das geht jetzt schon mit: `Java%` oder `%Script`. Eventuell sollten wir das zum Standardverhalten machen.
`<snip>`
Die Suche ist aber jetzt schon manchmal zu langsam. Da muss sich also mal jemand Gedanken machen, wie man das effizient hinkriegt.

**Comment by syslock** [comment]
Phrasensuche implementiert mit 62b47c6d84e7258ceecd344afb360ec624a4b501
Den zusätzlichen Vorschlag zu Teilwortsuche können wir bis auf weiteres nicht automatisiert umsetzen, bis jemand eine intelligente Idee hat wie, ohne dass die Suche langsam wird oder unerwartete Ergebnisse zurück liefert. Bis dahin muss man manuell mit der beschriebenen Wildcard-Methode vorgehen.
